theme: minima
title: Data monitoring
author: GitHub User
email: nacho@beepbeep.technology
description: > # this means to ignore newlines until "baseurl:"
  Here an awesome description for my new site. We can edit this
  line in _config.yml. It will appear in our document head meta (for
  Google search results) and in our feed.xml site description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
